lang: en-US
# color_scheme: light dark
title: Your post listing page title
# url: https://jekyll-theme-plain-text.github.io
# license_url: https://creativecommons.org/licenses/by-sa/4.0/

permalink: /:title

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

optional_front_matter:
  remove_originals: true
