#
# Uncomment the following lines and specify the title, language, and license URL of your blog.
#

# title: Your Blog Title
# lang: en
license_url: https://creativecommons.org/licenses/by-sa/4.0/

defaults:
  - scope:
      path: posts
    values:
      layout: post-page
      permalink: /:basename

theme: null

optional_front_matter:
  remove_originals: true
