lang: en
charset: utf-8
# color_scheme: light dark
viewport: width=device-width, initial-scale=1

title: The Blank Jekyll theme # Your post listing page title

# url: https://jekyll-theme-plain-text.github.io
# license_url: https://creativecommons.org/licenses/by-sa/4.0/

permalink: /:title

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: plain-text-post

optional_front_matter:
  remove_originals: true
