title: 金野裕希

defaults:
  - scope:
      path: ''
    values:
      layout: default

defaults:
  - scope:
      path: posts
    values:
      categories: posts
      permalink: /:basename

optional_front_matter:
  remove_originals: true
