# lang: ja
# charset: 
# color_scheme: false # disables auto dark mode
# viewport: 

title: The Blank Jekyll theme # Your page/post listing page title

# url: https://jekyll-theme-blank.github.io
# canonical_url: false # disables canonical URLs
license_url: https://creativecommons.org/licenses/by-sa/4.0/

permalink: /:title

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: plain-text-post

optional_front_matter:
  remove_originals: true

# remote_theme: jekyll-theme-blank/jekyll-theme-blank # Uncomment this line
