###
### Uncomment the following lines and specify the title, language, and license URL of your blog (all are optional).
###
# title: Your Blog Title
# lang: en
license_url: https://creativecommons.org/licenses/by-sa/4.0/

###
### DO NOT CHANGE ANYTHING AFTER THIS LINE.
###
defaults:
  - scope:
      path: posts
    values:
      layout: post-page
      permalink: /:basename

theme: null

optional_front_matter:
  remove_originals: true
