theme: null
title: 金野裕希
license_url: https://creativecommons.org/licenses/by-sa/4.0/

defaults:
  - scope:
      path: posts
    values:
      categories: [posts, unko]
      layout: page
      permalink: /:basename

optional_front_matter:
  remove_originals: true
