###
### Uncomment the following lines and specify the title, language code, and
### license URL of your blog (all are optional).
###

# title: Your awesome title
# lang: en
license_url: https://creativecommons.org/licenses/by-sa/4.0/

###
### DO NOT CHANGE ANYTHING BELOW THIS LINE UNLESS YOU MEAN TO.
###

permalink: /:title

# Disable the "minima" theme. Jekyll will apply it by default and load
# unnecessary `/assets/css/style.css'.
# cf. https://github.com/jekyll/minima
# cf. https://github.com/github/pages-gem/blob/c6182087cff795e0f4ba3c9f1373756f7cd0726d/lib/github-pages/configuration.rb#L107
theme: null

# cf. https://github.com/benbalter/jekyll-optional-front-matter
optional_front_matter:
  remove_originals: true
