lang: en
# charset: 
# color_scheme: light dark
# viewport: 

title: The Blank Jekyll theme # Your post listing page title

# url: https://jekyll-theme-blank.github.io
# canonical_url: false # disables the output of the `<link rel="canonical" href="...">` tag
# license_url: https://creativecommons.org/licenses/by-sa/4.0/

permalink: /:title

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: plain-text-post

optional_front_matter:
  remove_originals: true
