# Site title
title: Your awesome title

# Site language
lang: en-US

# Site license url
# license_url: https://creativecommons.org/licenses/by-sa/4.0/

# Permalink structure
permalink: /:title

# https://github.com/benbalter/jekyll-optional-front-matter#removing-originals
# optional_front_matter:
#  remove_originals: true
