lang: en-US
# color_scheme: light dark
title: Your post listing page title
# license_url: https://creativecommons.org/licenses/by-sa/4.0/

permalink: /:title

optional_front_matter:
  remove_originals: true
