# lang: en
# charset: utf-8
# color_scheme: false # disables auto dark mode
# viewport: width=device-width, initial-scale=1
title: Your index page title
# url: https://USERNAME.github.io
# canonical_url: false # disables canonical URLs
# license_url: https://creativecommons.org/licenses/by-sa/4.0/

permalink: /:title

collections:
  pages:
    output: true
    permalink: /:title/

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

optional_front_matter:
  remove_originals: true
